- .github/config/license.yml
- .github/workflows/licence.yml
Signed-off-by: tison <wander4096@gmail.com>
> ci: license checker

- README.md
to fix the markdown rendering and make a brief introduction to online bulk load
> README.md: update descriptions for online bulk load

- .github/workflows/test.yml
- online-bulk-load/pom.xml
- online-bulk-load/src/test/scala/org/tikv/bulkload/RawKVBulkLoaderSuite.scala
close https://github.com/tikv/migration/issues/6
> add ci test for bulk load

- online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala
close https://github.com/tikv/migration/issues/23
add ingest retry
> Ingset: fix peer is not leader

- online-bulk-load/src/main/scala/org/tikv/bulkload/example/BulkLoadExample.scala
close https://github.com/tikv/migration/issues/26
> fix More than Int.MaxValue elements

- online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala
During ingest we will let TiKV under `Import Mode`, also we will let PD under `pause region merge` status.
But we cannot assume that regions never merge or split, cause it will happen under some conditions, e.g. split region is called.
So we need add retry logic here.
> add retry when region merge or split

- .github/config/license.yml
- .github/workflows/build.yml
- .github/workflows/test.yml
- online-bulk-load/.scalafmt.conf
- online-bulk-load/README.md
- online-bulk-load/pom.xml
- online-bulk-load/src/main/scala/org/tikv/bulkload/PartitionNotFound.scala
- online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala
- online-bulk-load/src/main/scala/org/tikv/bulkload/RegionPartitioner.scala
- online-bulk-load/src/main/scala/org/tikv/bulkload/example/BulkLoadExample.scala
- online-bulk-load/src/test/scala/org/tikv/bulkload/RawKVBulkLoaderSuite.scala
close https://github.com/tikv/migration/issues/35
1. To format the code, please run `mvn mvn-scalafmt_2.12:format` or `mvn clean package -DskipTests`.
2. check format in CI
> enable code format

- online-bulk-load/README.md
Signed-off-by: tangjk <tangjiankun1226@gmail.com>
> change mvn compiling path or it will be error

- online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala
Signed-off-by: Peng Guanwen <pg999w@outlook.com>
Part of https://github.com/tikv/client-java/issues/268
> Pause merge when importing

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Signed-off-by: Jian Zhang <zjsariel@gmail.com>
close #16, add PR and issue template
> [close #16] add PR and issue template

- cdc/pkg/tcpserver/tcp_server_test.go
Issue Number: close #57
Problem Description: **CDC & BR CI failed**
Fix wrong path of certificants.
- Unit test
> [close #57]Fix CI cdc-ut

- br/pkg/mock/mock_cluster.go
- br/pkg/utils/pprof.go
Signed-off-by: Jian Zhang <zjsariel@gmail.com>
Issue Number: [to #67]
Problem Description: gosec failed on BR directory
the original hint which indicates gosec not to check the didn't work, changed them to a work one.
- No code
- No code
> [to #67] fix gosec failure for BR

- br/Makefile
Fix CI timeout of TiKV-BR
Issue Number: ref #57 
Problem Description: CDC & BR CI failed. See the [CI error](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3584/pipeline/) for detail
Increasing timeout by set `--timeout 5m` parameter.
- No code
- No
- No
> [to #57] br: fix CI timeout

- .github/workflows/ci-gc-worker.yml
- gc-worker/Makefile
- gc-worker/cmd/main.go
- gc-worker/server/server.go
Issue Number: close #94 
Add gosec and golang-lint check for gc-worker
- Unit test
> [close #94] GC-Worker gosec and golang-lint check

- br/pkg/restore/client.go
Issue Number: close #98 
restore files count is taken into collector and display it when printing summary.
Test Result is as following:
> [fix #98] fix br restore summary issue

- gc-worker/go.mod
- gc-worker/go.sum
- gc-worker/server/server.go
- gc-worker/server/server_test.go
Issue Number: close #100 
Problem Description:
support current pd's safepoint update interface
UpdateServiceGCSafePoint
UpdateGCSafePoint
- Unit test
> [fix #100] support current pd's safepoint update interface

- .github/workflows/br_release.yml
Issue Number: close #112 
add br release action
- No code
> [close #112] add br release action

- .github/workflows/br_release.yml
- .github/workflows/ci-br.yml
- br/Makefile
- br/README.md
- br/cmd/br/debug.go
- br/go.mod
- br/go.sum
- br/pkg/restore/import.go
- br/pkg/task/backup_raw.go
- br/pkg/task/restore_raw.go
- br/tools/check/go.mod
Issue Number: close #119 
Problem Description: Upgrade to go1.18 in TiKV-BR
Upgrade to go1.18 in TiKV-BR
- No code
- Unit test
> [close #119] Upgrade to go1.18 in TiKV-BR

- cdc/cdc/owner/changefeed.go
- cdc/cdc/owner/changefeed_test.go
- cdc/cdc/owner/scheduler.go
- cdc/cdc/owner/scheduler_test.go
- cdc/cdc/owner/scheduler_v1.go
- cdc/cdc/owner/scheduler_v1_test.go
Issue Number: close #121 
Some unit tests in model Owner don't run.
Add  func Test(t *testing.T)
- Unit test
> fix owner ut

- cdc/Makefile
- cdc/cdc/http_status_test.go
- cdc/cdc/kv/client.go
- cdc/cdc/kv/client_test.go
- cdc/cdc/kv/region_worker.go
- cdc/cdc/model/kv.go
- cdc/cdc/model/mounter.go
- cdc/cdc/owner/scheduler.go
- cdc/cdc/owner/scheduler_v1.go
- cdc/cdc/processor/pipeline/keyspan.go
- cdc/cdc/processor/pipeline/puller.go
- cdc/cdc/processor/pipeline/sink.go
- cdc/cdc/processor/processor.go
- cdc/cdc/puller/puller.go
- cdc/cdc/sink/buffer_sink.go
- cdc/cdc/sink/keyspan_sink.go
- cdc/cdc/sink/tikv.go
- cdc/errors.toml
- cdc/go.mod
- cdc/go.sum
- cdc/metrics/grafana/tikv-cdc.json
- cdc/pkg/cmd/server/server.go
- cdc/pkg/errors/errors.go
- cdc/pkg/regionspan/span.go
- cdc/pkg/util/ctx.go
- cdc/pkg/util/ctx_test.go
- cdc/pkg/version/version.go
- cdc/scripts/add-leaktest.sh
Issue Number: to #48 
Problem Description: TiKV CDC Development
1. Fix `keyspanPipelineImpl.ResolvedTs()` to make resolved-ts works.
2. Fix some `KeySpanID` missing.
3. Implement a most simple scheduler to make other codes working first.
4. Add tracing logs.
5. Make Grafana works.
6. Other refines.
- Unit test
> [to #48] cdc: Refine codes

- cdc/Makefile
- cdc/cdc/sink/sink.go
- cdc/cdc/sink/tikv.go
- cdc/cdc/sink/tikv_test.go
Issue Number: to #48
Problem Description: TiKV CDC Development
1. Remove BatchPut and combine to BatchPutWithTTL
2. Remove separate batch for put & delete to keep order of entries.
3. Improve process for expired ts.
4. Add unit tests.
- Unit test
> [to #48] Refine TiKV sink

- cdc/cdc/sink/metrics.go
- cdc/cdc/sink/statistics.go
- cdc/cdc/sink/tikv.go
- cdc/metrics/grafana/tikv-cdc.json
Issue Number: close #48
Problem Description: TiKV CDC Development
Add Grafana panels for TiKV sink.
- Unit test
> [to #48] cdc: Add Grafana panels for TiKV sink

- .github/workflows/ci-br.yml
- .github/workflows/ci-cdc.yml
- .github/workflows/ci-gc-worker.yml
- cdc/README.md
Issue Number: close #135 
Problem Description: The badges in README.md is incorrect
Fix the badges.
Also change CI names to distinct different workflows.
See [rendered](https://github.com/pingyu/migration/blob/fix-badge/cdc/README.md).
- No code
- No code
> [close #135] *: Fix the badges in README.md

- cdc/cdc/sink/sink.go
- cdc/cdc/sink/sink_test.go
- cdc/cdc/sink/tikv.go
- cdc/go.mod
- cdc/go.sum
- cdc/pkg/cmd/cli/cli_changefeed_create.go
check the format of sink url, when create changefeed.
Issue Number: close #137
see issue #137
add check for the format of sink url.
- Unit test
> [fix #137] check sink url

- cdc/cdc/sink/buffer_sink.go
- cdc/cdc/sink/buffer_sink_test.go
Some entry which cmmit_ts greater then resolved ts may send to dst tikv
Issue Number: close #153
Some entry which cmmit_ts greater than resolved ts may send to dst tikv
Only send entry which commit_ts less than resolved ts
- Has exported variable/fields change
- Has interface methods change
- Has persistent data change
- No code
- Unit test
> [fix #153] cdc: fix buffer sink

- cdc/pkg/version/check.go
Issue Number: close #issue_number
- Has exported variable/fields change
- Has interface methods change
- Has persistent data change
- No code
- Unit test
- No code
- Possible performance regression, WHY: **TBD**
- Increased code complexity, WHY: **TBD**
- Breaking backward compatibility, WHY: **TBD**
- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note
> [close #198] modify version check to be compatible for v6.2.0

- cdc/cdc/processor/pipeline/sorter.go
show flow control memory better
Issue Number: close #255
see issue #255 
- Unit test
> [fix #255] show flow control memory better

- cdc/metrics/grafana/tikv-cdc.json
fix changefeed metric show
Issue Number: close #257
see issue#257
- Has exported variable/fields change
- Has interface methods change
- Has persistent data change
- No code
- Unit test
> [fix #257] fix changefeed metric show

- cdc/metrics/grafana/tikv-cdc.json
fix metric `Sink write rows count/s` show wrong name
Issue Number: close #278
`total` -> `{{changefeed}}`
- No code
> [fix #278] fix metric `Sink write rows count/s` show wrong name

- cdc/cdc/sink/sink_test.go
- cdc/cdc/sink/tikv.go
Issue Number: close #238
create tikv client first
- Unit test
> [fix #238] fix tikv sink

- cdc/tests/integration_tests/kill_downstream/run.sh
Issue Number: close #283
Add integration test case for kill downstream
- No code
- Unit test
> [close #283] add it for kill downstream

- cdc/tests/integration_tests/_utils/check_count
- cdc/tests/integration_tests/_utils/check_sync_diff
- cdc/tests/integration_tests/cdc_hang_on/run.sh
- cdc/tests/integration_tests/changefeed_error/run.sh
- cdc/tests/integration_tests/kill_owner/run.sh
- cdc/tests/integration_tests/run_group.sh
- cdc/tests/integration_tests/sigstop/run.sh
- cdc/tests/utils/rawkv_data/checksum.go
- cdc/tests/utils/rawkv_data/gen_data.go
- cdc/tests/utils/rawkv_data/main.go
Issue Number: close #321
add `sending sigstop` test case
- No code
- No code
- **Functionality**. The pull request should implement what the author intends to do and fit …
> [fix #321] add `sending sigstop` test case

- cdc/Makefile
- cdc/tests/integration_tests/_utils/check_count
- cdc/tests/integration_tests/_utils/check_sync_diff
- cdc/tests/integration_tests/_utils/start_tidb_cluster
- cdc/tests/integration_tests/_utils/start_tidb_cluster_impl
- cdc/tests/integration_tests/_utils/start_tls_tidb_cluster
- cdc/tests/integration_tests/_utils/start_tls_tidb_cluster_impl
- cdc/tests/integration_tests/_utils/stop_tidb_cluster
- cdc/tests/integration_tests/cdc_hang_on/run.sh
- cdc/tests/integration_tests/sigstop/run.sh
- cdc/tests/tests.Dockerfile
Signed-off-by: Ping Yu <yuping@pingcap.com>
Issue Number: close #334 
Problem Description: G10 (sink_hang + sigstop) run more than 25 minutes
- Skip `check_count 2 "pd"` after `kill -19 pd-server`.
See https://github.com/tikv/migration/issues/334#issuecomment-1425997573
- Prolong sleep duration of `check_sync_diff`
As the original `1s` is not enough. See https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fmigration%2Fpull_integration_test/detail/pull_integration_test/77/pipeline/336.
- Add `timeout` for `lsof` as `lsof` has chances to take a long time due to unknown reason (maybe container environment ?).
- Other polish
Please follow these principles to …
> [close #334] tests: fix timeout of integration test `sigstop`

- cdc/go.mod
- cdc/go.sum
Issue Number: close #333
Problem Description: **cdc: Memory leak**
Upgrade `client-go` to solve context leak.
See https://github.com/pingyu/client-go/pull/1/commits/72cc631f446db90f7c40d92b1d49d10331680b2a, https://github.com/pingyu/client-go/pull/1, and https://github.com/tikv/client-go/pull/704
The memory leak issue #333  has not been completely solved.
A similar leak point was found in `BatchDelete`. See the call graph:
- Unit test
- Possible performance regression, WHY: **TBD**
- Increased code complexity, WHY: **TBD**
- Breaking backward compatibility, WHY: **TBD**
- **Concentration**. One pull request …
> [close #333] Fix context leak in BatchDelete

- .github/workflows/ci-br.yml
- br/pkg/backup/client.go
Issue Number: close #346 
Problem Description: **Backup failed when cluster is scaling**
Logs said that the reason of failure is:
> [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster
This PR add retry to `GetTS` to address the issue.
- No.
- **Tests**. A pull request should be test covered, whether the tests are unit tests, integration tests, or end-to-end tests. Tests should be sufficient, …
> [to #346] Improve fault tolerance for TSO

- cdc/Makefile
Issue Number: close #355 
Problem Description: **ci: error obtaining VCS status: exit status 128**
Update to latest `gotestsum`.
- No code
- No code
- **Functionality**. The pull request should implement what the author intends to do and fit well in …
> [close #355] chore: use latest gotestsum

- cdc/Makefile
Issue Number: close #409
Problem Description: **build: Cannot re-download 3rd binaries after "make clean"**
- Remove "prepare_test_binaries" flag in `make clean`.
- No code
- **Functionality**. The pull request should implement …
> [close #409] build: Remove "prepare_test_binaries" flag
