tikv/migration

online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala, online-bulk-load/src/main/scala/org/tikv/bulkload/example/BulkLoadExample.scala
close https://github.com/tikv/migration/issues/21
`sortByKey` is too slow and it is not needed.
We can just delete it.
=> remove sortbykey

online-bulk-load/src/main/scala/org/tikv/bulkload/PartitionNotFound.scala, online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala, online-bulk-load/src/main/scala/org/tikv/bulkload/RegionPartitioner.scala, online-bulk-load/src/main/scala/org/tikv/bulkload/example/BulkLoadExample.scala
use binary search to find partition
before: shuffle cost 8.4min
after: shuffle cost 20s
=> use binary search to find partition

online-bulk-load/src/main/scala/org/tikv/bulkload/RawKVBulkLoader.scala, online-bulk-load/src/main/scala/org/tikv/bulkload/example/BulkLoadExample.scala, online-bulk-load/src/test/scala/org/tikv/bulkload/RawKVBulkLoaderSuite.scala
close https://github.com/tikv/migration/issues/30
client-java support deduplicate key in this PR https://github.com/tikv/client-java/pull/276
=> remove duplicate key after sorting

cdc/tests/integration_tests/_utils/start_tidb_cluster_impl, cdc/tests/integration_tests/_utils/start_tls_tidb_cluster_impl
Signed-off-by: Ryan Leung <rleungx@gmail.com>
Issue Number: Ref tikv/pd#4679
`/pd/health` has been deprecated for a long time. Use `/pd/api/v1/health` instead.
- No code
=> Replace the deprecated health API

br/go.mod, br/go.sum
Signed-off-by: Jian Zhang <zjsariel@gmail.com>
Issue Number: [to #66]
1. https://github.com/pingcap/kvproto/pull/888 introduced `dst_api_version` in backup request, it hasn't been used in the current br tools.
2. BR depends on pd client, tidb, client-go, etc. the dependency is complicated which makes the upgrading progress complicated.
because the dependency is hard to update, I just simply update the kvproto in the following method:
1. check out a new branch of kvproto whose last commit is `78a55fb8e69c`, it is maintained in the `feature/br-api-v2` branch of [zz-jason/kvproto](https://github.com/zz-jason/kvproto/tree/feature/br-api-v2) repo
2. cherru-pick https://github.com/pingcap/kvproto/pull/888 to the new branch. 
3. replace the dependency of …
=> [to #66] update kvproto to support api v2

.github/workflows/ci-br.yml, br/Makefile
Signed-off-by: Jian Zhang <zjsariel@gmail.com>
Issue Number: [to #67]
Problem Description: the current Makefile is hard to understand and maintain
this pr reformatted the Makefile to make it readable to reduce the maintenance burden in the following methods:
- targets to build binaries are in a common namespace `build`, for example, `build/golangci-lint`, `build/gocov`, `build/failpoint-ctl`, etc.
- removed the `unit_test_in_verify_ci` build target since it's duplicated with the `test` target
this pr also altered the github actions for CI to utilize Makefile so that the build target in the Makefile itself is tested by github actions as well
- No code
- Unit test
=> [to #67] clean Makefile

br/cmd/br/backup.go, br/cmd/br/cmd.go, br/cmd/br/main.go, br/cmd/br/restore.go, br/pkg/storage/azblob.go, br/pkg/storage/gcs.go, br/pkg/storage/s3.go, br/pkg/task/backup.go, br/pkg/task/backup_raw.go, br/pkg/task/common.go, br/pkg/task/restore.go, br/pkg/task/restore_raw.go
Issue Number: close #104 
clean command args as descriped in https://pingcap.feishu.cn/docs/doccnCay8PSAR5uiw6RhlXEVz7b.
- Unit test
-
=> [fix #104]clean br command args

br/cmd/br/debug.go, br/pkg/backup/client.go, br/pkg/backup/client_test.go, br/pkg/checksum/executor.go, br/pkg/conn/conn.go, br/pkg/conn/conn_test.go, br/pkg/restore/client.go, br/pkg/task/backup_raw.go, br/pkg/task/common.go, br/pkg/task/common_test.go, br/pkg/task/restore_raw.go
Issue Number: close #108 
Checksum maybe mismatch if data expired during backup/restore.
1. Add a warning that "Warning: TiKV cluster is TTL enabled, checksum may be mismatch if some data expired during backup/restore."
2. Implement checksum debug command.
3. Add api version check to reject the invalid backup/restore operation.
- Unit test
=> [close #108] Br debug checksum cmd

cdc/cdc/kv/client_test.go
Issue Number: close #128 
Problem Description: [`clientSuite.TestClientErrNoPendingRegion`](https://github.com/tikv/migration/blob/b3c6c9b059588edb5f38a2b7a8868c71d1a5a2bc/cdc/cdc/kv/client_test.go#L2848) is not stable.
Make test cases in [`clientSuite`](https://github.com/tikv/migration/blob/main/cdc/cdc/kv/client_test.go) be serial.
Move `baseAllocatedID` to be acquired before `EventFeed` goroutine to ensure the correctness of base value.
Note that I'm not sure this PR will fix the issue. Although I re-run the CI and all of them are successful. If the failure happen again, reopen the issue.
- Unit test
=> [close #128] Fix TestClientErrNoPendingRegion

cdc/Makefile, gc-worker/Makefile
Issue Number: close #145 
Problem Description:  change binary name to support product release.
1. change cdc binary name to tikv-cdc
2. change gc-worker binary name to tikv-gc-worker
tag name is defined as `br-v1.0.0` `cdc-v1.0.0` `gc-worker-v1.0.0` to distinguish different products.
release test is as following in my private repos:  
- No code
- No code
=> [close #145] Change binary name to support product release

cdc/cdc/capture/http_handler.go, cdc/cdc/model/http_model.go, cdc/cdc/model/owner.go, cdc/cdc/model/owner_test.go, cdc/pkg/cmd/cli/cli_processor_query.go
fix processor query
Issue Number: close #164
The start-key and end-key in the result returned by the command tikv-cdc processor query are nil.
Use map[KeySpanID]*KeySpanReplicaInfo instead of []KeySpanID as result.
- Unit test
=> [close #164] Fix processor query

cdc/cdc/kv/client_test.go
Issue Number: close #177 
Problem Description: `client_test.TestHandleError` is not stable.
The issue seems to be caused by the insufficient of the 3 seconds' waiting duration. Maybe the CI env is busy.
Just prolong the duration to 10 seconds.
- Unit test
=> [close #177] fix unstable client_test

br/pkg/version/version.go, br/pkg/version/version_test.go, cdc/Makefile, cdc/pkg/version/check.go
Issue Number: close #200 
1. New tag naming stype is br-vx.x.x or cdc-vx.x.x, which cause version check issue in BR and CDC
2. Remove `br` or `cdc` prefix before version check.
- Unit test
=> [close #200] CDC & BR version check with new tag naming style

cdc/deployments/tikv-cdc/config-templates/scale-out.example.yaml, cdc/deployments/tikv-cdc/config-templates/topology.example.yaml
Issue Number: close #211 
Problem Description: **Add config templates for TiUP**
- No code
- No code
=> [close #211] add config templates

.codecov.yml, cdc/manual-cn.md
Issue Number: close #213
Problem Description: **Request Chinese manual for China customers**
Add TiKV-CDC Chinese manual
- No code
- No code
=> [close #213] TiKV-CDC Chinese manual

cdc/README.md, cdc/deployments/tikv-cdc/config-templates/scale-out.example.yaml, cdc/deployments/tikv-cdc/config-templates/topology.example.yaml, cdc/manual-cn.md
Issue Number: close #222
Problem Description: **docs: Change TiUP related docs**
Change TiUP related docs & configuration templates.
Note that in TiUP, TiKV-CDC is using section `kvcdc` & `kvcdc_servers`.
Refer to https://github.com/pingcap/tiup/pull/2022.
- No code
- No code
=> [to #222] Change docs for TiUP

br/Dockerfile, br/README-cn.md, br/README.md
Issue Number: close #239 
Supply the paramater description in TiKV-BR README.md and README-cn.md
- No code
- No code
=> [close #239] Add gcttl and range in readme

sst-data-source/src/main/java/org/tikv/datasources/br/SSTDecoder.java
Issue Number: close #245
Problem Description: **In the project Spark SST Data Source , SSTDecoder class supports to be constructed with options and ReadOptions for rocksdb, but  it seems like doesn't work when reading from sst**
- Unit test
=> [close #245] update sstdecoder  with alternative options

cdc/Makefile, cdc/go.mod, cdc/go.sum
Issue Number: ref #250 
Problem Description: changefeed raise error "empty value is not supported"
Hack `client-go` temporarily, see diff: https://github.com/pingyu/client-go/commit/1c8762535c9b936391d2b06c1a29273088b4edc7
- Unit test
=> [to #250] Remove empty value check in client-go

cdc/metrics/grafana/tikv-cdc.json
add input event count metric for puller
Issue Number: close #253 
add input event count metric for puller
- No code
- Unit test
=> [close #253] add input event metric for puller

br/deployments/docker/Dockerfile
Issue Number: close #263 
Fix br docker build
=> [close #263] Fix br docker build

br/pkg/restore/client.go, br/pkg/restore/client_test.go, br/pkg/restore/import.go, br/pkg/task/restore_raw.go
Issue Number: close #267 
Restore does not send `SetDownloadSpeedLimitRequest`. 
- Unit test
=> [close #267] Fix restore ratelimit

cdc/go.mod, cdc/go.sum, cdc/tests/integration_tests/http_api/util/test_case.py, cdc/tests/utils/rawkv_data/gen_data.go
Issue Number: close #250
Problem Description: cdc: changefeed raise error "empty value is not supported"
* Remove empty value check in tikv/client-go. See https://github.com/tikv/client-go/pull/612 (It's a temporarily fix on personal fork. Will pull to master later)
* Modify integration test to generate test data with empty value
* Prolong sleep duration of "move_keyspan" test, as the original "5s" seems to be not enough. See [here](https://ci.pingcap.net/blue/organizations/jenkins/common-check/detail/common-check/108312/pipeline/).
=> [to #250] cdc: remove empty value check in client-go

cdc/pkg/cmd/cmd.go
Signed-off-by: Ping Yu <yuping@pingcap.com>
Issue Number: close #312
Problem Description: **command name in cli help is not correct**
Change `cdc` in prompt message to `tikv-cdc`
```bash
❯ bin/tikv-cdc --help
TiKV Change Data Capture
Usage:
tikv-cdc [command]
Available Commands:
cli         Manage replication task and TiKV-CDC cluster
help        Help about any command
server      Start a TiKV-CDC capture server
version     Output version information
Flags:
-h, --help   help for tikv-cdc
Use "tikv-cdc [command] --help" for more information about a command.
❯ bin/tikv-cdc cli --help
Manage replication task and TiKV-CDC cluster
Usage:
tikv-cdc cli [flags]
tikv-cdc cli …
```
=> [to #312] Fix command name

cdc/Makefile, cdc/go.mod, cdc/go.sum, cdc/tests/integration_tests/_utils/start_tidb_cluster_impl, cdc/tests/integration_tests/_utils/stop_tidb_cluster, cdc/tests/integration_tests/cdc_hang_on/run.sh, cdc/tests/integration_tests/flow_control/run.sh, cdc/tests/tests.Dockerfile
Signed-off-by: Ping Yu <yuping@pingcap.com>
Issue Number: close #333 
Problem Description: Memory leak
Update `client-go` version which has fixed this issue.
See https://github.com/tikv/client-go/pull/697
PR: https://github.com/pingyu/client-go/pull/1
Diff: https://github.com/pingyu/client-go/compare/6ec40fff4e31..74fe33153943
Cherry-pick:
- https://github.com/tikv/client-go/pull/612
- https://github.com/tikv/client-go/pull/673
- https://github.com/tikv/client-go/pull/697
- No code
- Unit test
- No code
- **Concentration**. One pull request should only do one thing. No matter how small it is, the change does …
=> [close #333] update client-go version to fix context leak

pom.xml
Issue Number: close #345 
Problem Description: **build: bulk load build failed**
- No code
- Unit test
- **Functionality**. The pull request should implement what the author intends to do and fit well in the existing code base, …
=> [close #345] build: fix client-java dependency

cdc/Makefile, cdc/cdc/http_status_test.go, cdc/cdc/kv/client.go, cdc/cdc/kv/metrics.go, cdc/cdc/kv/region_worker.go, cdc/cdc/processor/pipeline/keyspan.go, cdc/cdc/processor/pipeline/puller.go, cdc/metrics/grafana/tikv-cdc.json, cdc/pkg/cmd/cli/cli_changefeed_create_test.go, cdc/pkg/cmd/cli/cli_changefeed_update.go, cdc/pkg/cmd/cli/cli_changefeed_update_test.go, cdc/pkg/config/config_test_data.go, cdc/pkg/config/replica_config.go, cdc/pkg/config/replica_config_test.go, cdc/pkg/util/ctx.go, cdc/pkg/util/filter.go, cdc/pkg/util/filter_test.go, cdc/pkg/util/kv_filter.go, cdc/pkg/util/kv_filter_test.go, cdc/tests/integration_tests/_utils/check_total_kvs, cdc/tests/integration_tests/kv_filter/conf/changefeed.toml, cdc/tests/integration_tests/kv_filter/run.sh, cdc/tests/integration_tests/run_group.sh, cdc/tests/utils/rawkv_data/checksum.go, cdc/tests/utils/rawkv_data/gen_data.go, cdc/tests/utils/rawkv_data/main.go
Issue Number: close #348 
Problem Description: **Support filter for key or value**
- Add `kv_filter` to filter event match the pattern provided by user.
Add metric "filter-out" (the test case is that all events were filtered out):
- Unit test
- Need to update the documentation
- **Tests**. A pull request should be test covered, whether the tests are unit tests, integration tests, or end-to-end tests. …
=> [close #348] support filter for key & value

.golangci.yml, br/Makefile, br/pkg/backup/client.go, br/pkg/backup/client_test.go, br/pkg/storage/s3_test.go, cdc/Makefile, cdc/cdc/model/kv.go, cdc/pkg/fsutil/filelock.go
Issue Number: ref #371 
- Upgrade golangci-lint to v1.55.2 to address the lint error for #372, see https://github.com/tikv/migration/actions/runs/7069331510/job/19245442484
```
cdc/processor/processor_test.go:594:93: missing type in composite literal (typecheck)
c.Assert(p.changefeed.Workloads[p.captureInfo.ID], check.DeepEquals, model.TaskWorkload{1: {Workload: 1}, 2: {Workload: 1}})
^
pkg/cmd/cli/cli_changefeed_helper.go:119:2: forceRemoveOpt declared and not used (typecheck)
forceRemoveOpt := "false"
^
pkg/orchestrator/reactor_state_test.go:99:51: missing type in composite literal (typecheck)
"6bbc01c8-0605-4f86-a0f9-b3119109b225": {45: {Workload: 1}},
^
pkg/orchestrator/reactor_state_test.go:158:51: missing type in composite literal (typecheck) …
```
=> [to #371] chore: Upgrade golangci-lint to v1.55.2

.github/workflows/release_version.yml, cdc/Makefile
Issue Number: close #405
- Update go version to `1.21`
- Build arm64 artifacts.
- No code
- **Functionality**. The pull request should implement what the author intends …
=> [close #405] cd: Fix failure of CD and support to build arm64 artifact

.github/workflows/release_version.yml, br/Makefile, cdc/Makefile
Issue Number: close #407
Problem Description: **ci: Release arm64 artifact failed type/bug**
- Change env var `GOARCH` to `TARGET_ARCH`, then tools will be built for current arch.
```
❯ cd cdc
❯ make release
go generate
CGO_ENABLED=0 GOOS= GOARCH= GO111MODULE=on go build -buildvcs=false -trimpath  -ldflags '-X "github.com/tikv/migration/cdc/pkg/version.ReleaseVersion=v1.2-master-dirty" -X "github.com/tikv/migration/cdc/pkg/version.BuildTS=2024-06-16 13:27:51" -X "github.com/tikv/migration/cdc/pkg/version.GitHash=db0ae72b17d7f9b888b05745d4582cb11f345cc0" -X "github.com/tikv/migration/cdc/pkg/version.GitBranch=main" -X "github.com/tikv/migration/cdc/pkg/version.GoVersion=go …
```
=> [close #407] Fix arm64 build

.github/config/br_pd.toml, .github/config/br_rawkv.toml, br/Makefile, br/pkg/restore/client.go, br/pkg/restore/client_test.go, br/pkg/restore/split.go, br/pkg/restore/split_client.go, br/pkg/restore/split_test.go, br/pkg/restore/util.go, br/pkg/task/common.go, br/pkg/task/config.go, br/pkg/task/restore_raw.go, br/tests/rawkv/main.go, br/tests/rawkv/tikv_br.go
Issue Number: close #421
Problem Description: **br: split regions failed**
- Separate keys to smaller batch with maximum number of keys of `1024`.
- Add flags to specify split region max keys and allowed gRPC message size.
- Use `split-region-max-keys = 4` for integration tests.
- Adjust region split threshold to cover condition of more regions in integration tests.
- No.
Manually confirm the coverage of split region with max keys = `4` by logs of integration tests.
```
[2025/04/16 10:06:03.597 +08:00] [INFO] [split.go:134] ["get split keys for region"] [len=24] [region=354]
[2025/04/16 10:06:03.597 +08:00] [INFO] [split.go:157] ["split regions"] …
```
=> [close #421] br: Split for smaller batch of keys

.github/config/br_pd.toml, .github/config/br_rawkv.toml, .github/workflows/ci-br.yml, br/Makefile, br/pkg/restore/client.go, br/pkg/restore/split.go, br/pkg/restore/split_client.go, br/pkg/restore/split_test.go, br/pkg/restore/util.go, br/pkg/task/common.go, br/pkg/task/config.go, br/pkg/task/restore_raw.go, br/tests/rawkv/main.go, br/tests/rawkv/tikv_br.go
Cherry pick of #422
Issue Number: close #421
Problem Description: **br: split regions failed**
- Separate keys to smaller batch with maximum number of keys of `1024`.
- Add flags to specify split region max keys and allowed gRPC message size.
- Use `split-region-max-keys = 4` for integration tests.
- Adjust region split threshold to cover condition of more regions in integration tests.
- No.
Manually confirm the coverage of split region with max keys = `4` by logs of integration tests.
```
[2025/04/16 10:06:03.597 +08:00] [INFO] [split.go:134] ["get split keys for region"] [len=24] [region=354]
[2025/04/16 10:06:03.597 +08:00] [INFO] [split.go:157] ["split regions"] …
```
=> [close #421] [br-release-1.0] br: Split for smaller batch of keys (#422)

.github/workflows/release_version.yml, br/Makefile, cdc/Makefile
Cherry pick of #406, #408
Additional changes:
- Set `CGO_ENABLED=0` to enable cross platform building. The performance gap is not significant for `tikv-br`.
Issue Number: close #407
Problem Description: **ci: Release arm64 artifact failed type/bug**
- Change env var `GOARCH` to `TARGET_ARCH`, then tools will be built for current arch.
```
❯ cd br
➜  make release
CGO_ENABLED=0 GOOS= GOARCH= GO111MODULE=on go build -tags codes -ldflags '-X "github.com/tikv/migration/br/pkg/version/build.ReleaseVersion=br-v1.0.1-4-ge8313a7-dirty" -X "github.com/tikv/migration/br/pkg/version/build.BuildTS=2025-04-17 01:54:48" -X "github.com/tikv/migration/br/pkg/version/build.GitHash=e8313a70c5 …
```
=> [close #407] [br-release-1.0] Fix arm64 build

br/Makefile, cdc/Makefile
Issue Number: close #407
Problem Description: **ci: Release arm64 artifact failed type/bug**
- Set `CGO_ENABLED=0` to cross platform building. The perform gap is not significant for tikv-br.
- Fix the release version.
- No code
```
➜  make release
CGO_ENABLED=0 GOOS= GOARCH= GO111MODULE=on go build -tags codes -ldflags '-X "github.com/tikv/migration/br/pkg/version/build.ReleaseVersion=br-v1.1-master-dirty" -X "github.com/tikv/migration/br/pkg/version/build.BuildTS=2025-04-17 15:37:33" -X "github.com/tikv/migration/br/pkg/version/build.GitHash=49dcd7201fb0fb1d9d71c56ff37aae34d3923c63" -X "github.com/tikv/migration/br/pkg/version/build.GitBranch=main"' -o bin/tikv-br …
```
=> [close #407] br: Fix arm64 build
